bookproject/apps/books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('<slug:book>', views.single_book, name='single_book'),
    path('<slug:book_slug>/<slug:slug>', views.book_chapter, name='book_chapter'),
    path('authors/', views.catalog_author, name='catalog_author'),
    path('author/<slug:author>', views.single_author, name='single_author'),
    path('category/<slug:category>', views.category, name='category'),
]

bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('', include('accounts.urls', namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Читать Онлайн{% endblock %}</title>

  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&family=Spectral:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>


<body {% block bodyclass %}{% endblock %}>

  {% block header %}
    {% include 'header.html' %}
  {% endblock %}

  {% block content %}
  {% endblock %}

  {% block footer %}
    {% include 'footer.html' %}
  {% endblock %}

  {% block jquery %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  {% endblock %}
  {% block scripts %}{% endblock %}
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  <script src="https://unpkg.com/phosphor-icons"></script>

</body>
</html>

templates/header.html
<header id="header">
  <div class="container">

    <nav class="header-nav">
      <ul class="header-menu">
        <li><a href="{% url 'books:catalog' %}">Книги</a></li>
      </ul>
    </nav>
    <a href="{% url 'books:catalog' %}" class="header-logo">Читай онлайн!</a>
    <nav class="header-nav">
      <ul class="header-menu">
        <li><a href="{% url 'books:catalog_author' %}">Авторы</a></li>
      </ul>
    </nav>

    <div class="header-user">
      <span class="header-user-login">Войти</span>
      <span class="header-user-register">Регистрация</span>
    </div>

  </div>
</header>

{% include 'login.html' %}
{% include 'register.html' %}

templates/login.html
<div class="modal modal-login">
  <div class="register-form-container">
    <h3>Вход</h3>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label>
          <span>Имя пользователя</span>
          <input type="text" name="login_username" required>
          <p class="error">success</p>
        </label>
      </div>
      <div class="form-group">
        <label>
          <span>Пароль</span>
          <input type="text" name="login_password" required>
          <p class="error">success</p>
        </label>
      </div>
      <button class="btn" type="submit">Войти</button>
    </form>
    <div class="register-success msg-success">Вы успешно зарегистрировались!</div>
    <div class="register-error msg-error">Регистрация не удалась!</div>
  </div>
</div>

templates/register.html
<div class="modal modal-register">
  <div class="register-form-container">
    <h3>Регистрация</h3>
    <form action="" method="POST">
      {% csrf_token %}
      {% for field in register_form %}
        <div class="form-group">
          <label>
            <span>{{ field.label }}</span>
            {{ field }}
            <p class="error">success</p>
          </label>
        </div>
      {% endfor %}
      <button class="btn" type="submit">Создать</button>
    </form>
    <div class="register-success msg-success">Вы успешно зарегистрировались!</div>
    <div class="register-error msg-error">Регистрация не удалась!</div>
  </div>
</div>